#!/bin/bash

ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/gitignore_global ~/.gitignore_global

ln -s ~/dotfiles/vimrc ~/.vimrc
ln -sn ~/dotfiles/vimfiles ~/.vim

ln -s ~/dotfiles/irbrc ~/.irbrc

ln -s ~/dotfiles/ctags ~/.ctags

ln -s ~/dotfiles/eslintrc ~/.eslintrc

cd ~/dotfiles
git pull
git submodule update --init
cd -
