#!/bin/bash

ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/gitignore_global ~/.gitignore_global

ln -s ~/dotfiles/vimrc ~/.vimrc
ln -sn ~/dotfiles/vimfiles ~/.vim

cd ~/dotfiles
git pull
git submodule update --init
cd -
