#!/bin/bash

git -C ~/dotfiles pull
git -C ~/dotfiles submodule update --init

ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/gitignore_global ~/.gitignore_global

ln -s ~/dotfiles/vimrc ~/.vimrc
ln -sn ~/dotfiles/vimfiles ~/.vim

ln -s ~/dotfiles/irbrc ~/.irbrc

ln -s ~/dotfiles/ctags ~/.ctags

ln -s ~/dotfiles/eslintrc ~/.eslintrc
