vim.loader.enable()

vim.g.mapleader = ' '

require('core.options')
require('core.theme')
require('core.keymaps')
require('core.autocmds')

require('features.active_window_cursorline').setup()
require('features.scroll_navigation').setup()
require('features.window_sizing').setup()
require('features.coverflow').setup()
require('features.copy_path').setup()
require('features.find_in_files').setup()
require('features.terminal_quit_guard').setup()

require('plugins.fugitive').setup()
require('plugins.gitgutter').setup()
require('plugins.ctrlp').setup()
require('plugins.autopairs').setup()
require('plugins.nerdtree').setup()
require('plugins.projectionist').setup()
require('plugins.dadbod_ui').setup()
require('plugins.indent_object').setup()
require('plugins.emmet').setup()
require('plugins.resize_mode').setup()
require('plugins.ruby').setup()
require('plugins.rsi').setup()
require('plugins.ale').setup()
require('plugins.targets').setup()
require('plugins.closetag').setup()
require('plugins.markdown').setup()
require('plugins.textobj_entire').setup()
require('plugins.flash').setup()
require('plugins.window_picker').setup()
require('plugins.toggleterm').setup()
